vpc_cidr_block = "10.1.0.0/16"
name = "dev-vpc"
environment = "dev"
public_subnet_cidr_block = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet_cidr_block = ["10.1.3.0/24", "10.1.4.0/24"]
subnet_availability_zone = ["eu-central-1a", "eu-central-1b"]
public_subnet_name = "dev-vpc-public-subnet"
private_subnet_name = "dev-vpc-private-subnet"
public_rt_name = "dev-vpc-public-rt"
private_rt_name = "dev-vpc-private-rt"
postgres_db_sg_name = "dev-postgres-db-sg"
postgres_db_subnet_grp_name = "dev-postgres-subnet-group"
postgres_db_identifier = "dev-tedhelper-db"
postgres_db_name = "tedhelperDB"
# postgres_db_username = "postgres"
# postgres_db_password = "Y4bC9NErMz6GcE"
postgres_db_instance_class = "db.t3.micro"
postgres_db_tag_name = "tedhelper-db"
postgres_db_tag_application = "tedhelper"
api_gw_name = "dev-CleanerAPI"
alb_sg_name = "dev-alb-sg"
# alb_access_log_bucket_name = "sa-project-dev-alb-access-log-s3-bucket"
# alb_connection_log_bucket_name = "sa-project-dev-alb-connection-log-s3-bucket"
alb_name = "dev-alb"
tedhelper_target_group_name = "tedhelper-dev-alb-target-group"
tedhelper_port_for_lb_target_group = 8050
tedhelper_health_check_path = "/v3/api-docs"
tedsimulator_target_group_name = "tedsim-dev-alb-target-group"
tedsimulator_port_for_lb_target_group = 3000
tedsimulator_health_check_path = "/api/timesheets"
provider_port_for_lb_target_group = 5000
provider_health_check_path = "/api/v1/"
provider_target_group_name = "provider-dev-alb-target-group"
provider_mongodb_port_for_lb_target_group = 27017
provider_mongodb_health_check_path = "/"
provider_mongodb_target_group_name = "provider-dev-mongo-target-group"